const ASSETS = {
  // Backgrounds
  bg_forest: 'assets/backgrounds/forest.jpg',
  bg_desert: 'assets/backgrounds/desert.jpg',
  bg_ice_cave: 'assets/backgrounds/ice_cave.jpg',
  bg_castle: 'assets/backgrounds/castle.jpg',
  bg_netherworld: 'assets/backgrounds/netherworld.jpg',
  bg_forest_enhanced: 'assets/backgrounds/forest_enhanced.jpg',
  bg_desert_enhanced: 'assets/backgrounds/desert_enhanced.jpg',
  bg_ice_cave_enhanced: 'assets/backgrounds/ice_cave_enhanced.jpg',
  bg_castle_enhanced: 'assets/backgrounds/castle_enhanced.jpg',
  bg_netherworld_enhanced: 'assets/backgrounds/netherworld_enhanced.jpg',
  
  // Card back and frames
  cardBack: 'assets/cards/card_back.png',
  cardFrame: 'assets/cards/card_frame.png',
  cardFrameGold: 'assets/cards/card_frame_gold.png',
  cardFrameSilver: 'assets/cards/card_frame_silver.png',
  cardFrameBronze: 'assets/cards/card_frame_bronze.png',
  // FF Job Cards (20 generated by Laptop Hermes)
  B01_song_of_courage: 'assets/cards/B01_song_of_courage.png',
  B02_lullaby: 'assets/cards/B02_lullaby.png',
  B03_melody_of_healing: 'assets/cards/B03_melody_of_healing.png',
  BM01_fireball: 'assets/cards/BM01_fireball.png',
  BM02_ice_shard: 'assets/cards/BM02_ice_shard.png',
  BM03_thunder_bolt: 'assets/cards/BM03_thunder_bolt.png',
  D01_thrust: 'assets/cards/D01_thrust.png',
  D02_jump: 'assets/cards/D02_jump.png',
  D04_dragon_dive: 'assets/cards/D04_dragon_dive.png',
  DK01_soul_drain: 'assets/cards/DK01_soul_drain.png',
  DK02_dark_slash: 'assets/cards/DK02_dark_slash.png',
  DK03_blood_price: 'assets/cards/DK03_blood_price.png',
  T01_quick_stab: 'assets/cards/T01_quick_stab.png',
  T02_smoke_bomb: 'assets/cards/T02_smoke_bomb.png',
  T03_backstab: 'assets/cards/T03_backstab.png',
  W01_strike: 'assets/cards/W01_strike.png',
  W02_defend: 'assets/cards/W02_defend.png',
  W03_heavy_blow: 'assets/cards/W03_heavy_blow.png',
  WM01_holy_light: 'assets/cards/WM01_holy_light.png',
  WM02_protect: 'assets/cards/WM02_protect.png',
  WM03_cure: 'assets/cards/WM03_cure.png',
  BM04_arcane_missile: 'assets/cards/BM04_arcane_missile.png',
  BM05_meditate: 'assets/cards/BM05_meditate.png',
  BM06_blizzard: 'assets/cards/BM06_blizzard.png',
  BM07_meteor: 'assets/cards/BM07_meteor.png',
  BM08_mana_surge: 'assets/cards/BM08_mana_surge.png',
  BM10_ultima: 'assets/cards/BM10_ultima.png',
  T05_dagger_throw: 'assets/cards/T05_dagger_throw.png',
  T06_shadow_step: 'assets/cards/T06_shadow_step.png',
  T07_assassinate: 'assets/cards/T07_assassinate.png',
  T08_wind_dash: 'assets/cards/T08_wind_dash.png',
  T10_eternal_night: 'assets/cards/T10_eternal_night.png',
  W04_shield_bash: 'assets/cards/W04_shield_bash.png',
  W05_battle_cry: 'assets/cards/W05_battle_cry.png',
  W07_whirlwind: 'assets/cards/W07_whirlwind.png',
  W08_earthquake: 'assets/cards/W08_earthquake.png',
  W10_titans_wrath: 'assets/cards/W10_titans_wrath.png',
  WM04_smite: 'assets/cards/WM04_smite.png',
  WM05_prayer: 'assets/cards/WM05_prayer.png',
  WM06_divine_shield: 'assets/cards/WM06_divine_shield.png',
  WM07_holy: 'assets/cards/WM07_holy.png',
  WM08_resurrection: 'assets/cards/WM08_resurrection.png',
  // Characters
  warrior: 'assets/characters/warrior_portrait.png',
  mage: 'assets/characters/mage_portrait.png',
  thief: 'assets/characters/thief_portrait.png',
  cleric: 'assets/characters/cleric_portrait.png',
  // Enemies
  goblin: 'assets/enemies/goblin.png',
  skeleton: 'assets/enemies/skeleton.png',
  slime: 'assets/enemies/slime.png',
  wolf: 'assets/enemies/wolf.png',
  dark_mage: 'assets/enemies/dark_mage.png',
  golem: 'assets/enemies/golem.png',
  orc: 'assets/enemies/orc.png',
  harpy: 'assets/enemies/harpy.png',
  ghost: 'assets/enemies/ghost.png',
  fire_elemental: 'assets/enemies/fire_elemental.png',
  spider: 'assets/enemies/spider.png',
  bandit: 'assets/enemies/bandit.png',
  treant: 'assets/enemies/treant.png',
  merman: 'assets/enemies/merman.png',
  dark_knight: 'assets/enemies/dark_knight.png',
  boss_dragon: 'assets/enemies/boss_dragon.png',
  boss_lich: 'assets/enemies/boss_lich.png',
  boss_demon: 'assets/enemies/boss_demon.png',
  // Enhanced enemies
  enemy_goblin_warrior: 'assets/enemies/enemy_goblin_warrior.png',
  enemy_skeleton_knight: 'assets/enemies/enemy_skeleton_knight.png',
  enemy_slime_king: 'assets/enemies/enemy_slime_king.png',
  enemy_wolf_beast: 'assets/enemies/enemy_wolf_beast.png',
  enemy_dark_mage: 'assets/enemies/enemy_dark_mage.png',
  enemy_stone_golem: 'assets/enemies/enemy_stone_golem.png',
  enemy_orc_berserker: 'assets/enemies/enemy_orc_berserker.png',
  enemy_harpy: 'assets/enemies/enemy_harpy.png',
  enemy_ghost_wraith: 'assets/enemies/enemy_ghost_wraith.png',
  enemy_fire_elemental: 'assets/enemies/enemy_fire_elemental.png',
  enemy_giant_spider: 'assets/enemies/enemy_giant_spider.png',
  enemy_bandit_rogue: 'assets/enemies/enemy_bandit_rogue.png',
  enemy_treant: 'assets/enemies/enemy_treant.png',
  enemy_merman_warrior: 'assets/enemies/enemy_merman_warrior.png',
  enemy_dark_knight: 'assets/enemies/enemy_dark_knight.png',
  boss_lich_king: 'assets/enemies/boss_lich_king.png',
  boss_red_dragon: 'assets/enemies/boss_red_dragon.png',
  boss_demon_lord: 'assets/enemies/boss_demon_lord.png',
  // Enhanced backgrounds
  bg_forest_enhanced: 'assets/backgrounds/bg_forest_enhanced.jpg',
  bg_desert_enhanced: 'assets/backgrounds/bg_desert_enhanced.jpg',
  bg_ice_cave_enhanced: 'assets/backgrounds/bg_ice_cave_enhanced.jpg',
  bg_castle_enhanced: 'assets/backgrounds/bg_castle_enhanced.jpg',
  bg_netherworld_enhanced: 'assets/backgrounds/bg_netherworld_enhanced.jpg',
  // UI
  icon_attack: 'assets/ui/icon_attack.png',
  icon_defense: 'assets/ui/icon_defense.png',
  icon_draw: 'assets/ui/icon_draw.png',
  icon_gold: 'assets/ui/icon_gold.png',
  icon_hp: 'assets/ui/icon_hp.png',
  icon_mana: 'assets/ui/icon_mana.png',
};

let loadedAssets = {};
let assetsLoaded = false;

function loadAssets(callback) {
  const keys = Object.keys(ASSETS);
  if (keys.length === 0) { assetsLoaded = true; if (callback) callback(); return; }
  let loaded = 0;
  let failed = 0;
  keys.forEach(key => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      loadedAssets[key] = img;
      loaded++;
      if (loaded + failed === keys.length) { assetsLoaded = true; if (callback) callback(); }
    };
    img.onerror = () => {
      failed++;
      // Create placeholder for failed images
      loadedAssets[key] = null;
      if (loaded + failed === keys.length) { assetsLoaded = true; if (callback) callback(); }
    };
    img.src = ASSETS[key];
  });
  // Timeout fallback: after 10s, consider assets loaded regardless
  setTimeout(() => {
    if (!assetsLoaded) {
      assetsLoaded = true;
      if (callback) callback();
    }
  }, 10000);
}

function getEnemySprite(enemyKey) {
  const map = {
    skeleton: 'skeleton', bat: 'wolf', slime: 'slime', goblin: 'goblin',
    spider: 'spider', ghost: 'ghost', orc: 'orc', imp: 'dark_mage',
    mushroom: 'slime', knight: 'dark_knight', wraith: 'ghost',
    dark_paladin: 'dark_knight', twin_assassins: 'orc', golem: 'golem',
    vampire: 'dark_knight', harpy: 'harpy', fire_elemental: 'fire_elemental',
    bandit: 'bandit', treant: 'treant', merman: 'merman',
    lich: 'boss_lich', dragon: 'boss_dragon', void_entity: 'boss_demon'
  };
  return map[enemyKey] || 'skeleton';
}

function getCardArt(cardId) {
  // Map card IDs to asset file names
  var artMap = {
    // Warrior cards (W prefix)
    'golpe_rapido': 'W01_strike',
    'espadada': 'W02_defend',
    'investida': 'W03_heavy_blow',
    'golpe_brutal': 'W04_shield_bash',
    'corte_duplo': 'W05_battle_cry',
    'estocada': 'W07_whirlwind',
    // Black Mage cards (BM prefix)
    'fireball': 'BM01_fireball',
    'ice_shard': 'BM02_ice_shard',
    'thunder_bolt': 'BM03_thunder_bolt',
    'arcane_missile': 'BM04_arcane_missile',
    'blizzard': 'BM06_blizzard',
    'meteor': 'BM07_meteor',
    'mana_surge': 'BM08_mana_surge',
    'ultima': 'BM10_ultima',
    // Thief cards (T prefix)
    'quick_stab': 'T01_quick_stab',
    'smoke_bomb': 'T02_smoke_bomb',
    'backstab': 'T03_backstab',
    'dagger_throw': 'T05_dagger_throw',
    'shadow_step': 'T06_shadow_step',
    'assassinate': 'T07_assassinate',
    'wind_dash': 'T08_wind_dash',
    'eternal_night': 'T10_eternal_night',
    // White Mage cards (WM prefix)
    'holy_light': 'WM01_holy_light',
    'protect': 'WM02_protect',
    'cure': 'WM03_cure',
    'smite': 'WM04_smite',
    'prayer': 'WM05_prayer',
    'divine_shield': 'WM06_divine_shield',
    'holy': 'WM07_holy',
    'resurrection': 'WM08_resurrection',
    // Dragoon cards (D prefix)
    'thrust': 'D01_thrust',
    'jump': 'D02_jump',
    'polearm_slash': 'D03_polearm_slash',
    'dragon_dive': 'D04_dragon_dive',
    'spear_mastery': 'D05_spear_mastery',
    'impale': 'D06_impale',
    'dragoon_oath': 'D07_dragoon_oath',
    'skyfall_spear': 'D08_skyfall_spear',
    'lancet': 'D09_lancet',
    'high_jump': 'D10_high_jump',
    // Dark Knight cards (DK prefix)
    'soul_drain': 'DK01_soul_drain',
    'dark_slash': 'DK02_dark_slash',
    'blood_price': 'DK03_blood_price',
    'shadow_strike': 'DK04_shadow_strike',
    'dark_armor': 'DK05_dark_armor',
    'soul_reaver': 'DK06_soul_reaver',
    'dark_pact': 'DK07_dark_pact',
    'abyssal_blade': 'DK08_abyssal_blade',
    'living_dead': 'DK09_living_dead',
    'chaos_dark': 'DK10_chaos_dark',
    // Bard cards (B prefix)
    'song_of_courage': 'B01_song_of_courage',
    'lullaby': 'B02_lullaby',
    'melody_of_healing': 'B03_melody_of_healing',
    'inspire': 'B04_inspire',
    'battle_hymn': 'B06_battle_hymn',
    'sonic_boom': 'B07_sonic_boom',
    'encore': 'B08_encore',
    'symphony': 'B09_symphony',
    'eternal_song': 'B10_eternal_song',
    // Neutral cards (N prefix)
    'arcane_intellect': 'N01_arcane_intellect',
    'mana_burst': 'N02_mana_burst',
    // Additional warrior cards
    'escudo_reforcado': 'W04_shield_bash',
    'barreira_gelo': 'W05_battle_cry',
    'foco': 'W07_whirlwind',
    'preparacao': 'W08_earthquake',
    'esquiva': 'T02_smoke_bomb',
    'forca_interior': 'N01_arcane_intellect',
    'titans_wrath': 'W10_titans_wrath'
  };
  var artKey = artMap[cardId] || cardId;
  if (loadedAssets[artKey]) return loadedAssets[artKey];
  return null;
}