const ASSETS = {
  cardBack: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/card_back.png',
  cardFrame: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/card_frame.png',
  // FF Job Cards (20 generated by Laptop Hermes)
  B01_song_of_courage: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/B01_song_of_courage.png',
  B02_lullaby: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/B02_lullaby.png',
  B03_melody_of_healing: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/B03_melody_of_healing.png',
  BM01_fireball: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/BM01_fireball.png',
  BM02_ice_shard: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/BM02_ice_shard.png',
  BM03_thunder_bolt: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/BM03_thunder_bolt.png',
  D01_thrust: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/D01_thrust.png',
  D02_jump: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/D02_jump.png',
  D04_dragon_dive: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/D04_dragon_dive.png',
  DK01_soul_drain: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/DK01_soul_drain.png',
  DK02_dark_slash: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/DK02_dark_slash.png',
  DK03_blood_price: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/DK03_blood_price.png',
  T01_quick_stab: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/T01_quick_stab.png',
  T02_smoke_bomb: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/T02_smoke_bomb.png',
  T03_backstab: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/T03_backstab.png',
  W01_strike: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/W01_strike.png',
  W02_defend: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/W02_defend.png',
  W03_heavy_blow: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/W03_heavy_blow.png',
  WM01_holy_light: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/WM01_holy_light.png',
  WM02_protect: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/WM02_protect.png',
  WM03_cure: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/WM03_cure.png',
  BM04_arcane_missile: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/BM04_arcane_missile.png',
  BM05_meditate: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/BM05_meditate.png',
  BM06_blizzard: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/BM06_blizzard.png',
  BM07_meteor: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/BM07_meteor.png',
  BM08_mana_surge: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/BM08_mana_surge.png',
  BM10_ultima: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/BM10_ultima.png',
  T05_dagger_throw: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/T05_dagger_throw.png',
  T06_shadow_step: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/T06_shadow_step.png',
  T07_assassinate: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/T07_assassinate.png',
  T08_wind_dash: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/T08_wind_dash.png',
  T10_eternal_night: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/T10_eternal_night.png',
  W04_shield_bash: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/W04_shield_bash.png',
  W05_battle_cry: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/W05_battle_cry.png',
  W07_whirlwind: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/W07_whirlwind.png',
  W08_earthquake: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/W08_earthquake.png',
  W10_titans_wrath: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/W10_titans_wrath.png',
  WM04_smite: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/WM04_smite.png',
  WM05_prayer: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/WM05_prayer.png',
  WM06_divine_shield: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/WM06_divine_shield.png',
  WM07_holy: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/WM07_holy.png',
  WM08_resurrection: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/cards/WM08_resurrection.png',
  // Characters
  warrior: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/characters/warrior_portrait.png',
  mage: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/characters/mage_portrait.png',
  thief: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/characters/thief_portrait.png',
  cleric: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/characters/cleric_portrait.png',
  // Enemies
  goblin: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/goblin.png',
  skeleton: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/skeleton.png',
  slime: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/slime.png',
  wolf: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/wolf.png',
  dark_mage: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/dark_mage.png',
  golem: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/golem.png',
  orc: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/orc.png',
  harpy: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/harpy.png',
  ghost: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/ghost.png',
  fire_elemental: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/fire_elemental.png',
  spider: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/spider.png',
  bandit: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/bandit.png',
  treant: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/treant.png',
  merman: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/merman.png',
  dark_knight: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/dark_knight.png',
  boss_dragon: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/boss_dragon.png',
  boss_lich: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/boss_lich.png',
  boss_demon: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/enemies/boss_demon.png',
  // Backgrounds
  bg_forest: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/backgrounds/forest.jpg',
  bg_desert: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/backgrounds/desert.jpg',
  bg_ice_cave: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/backgrounds/ice_cave.jpg',
  bg_castle: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/backgrounds/castle.jpg',
  bg_netherworld: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/backgrounds/netherworld.jpg',
  // UI
  icon_attack: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/ui/icon_attack.png',
  icon_defense: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/ui/icon_defense.png',
  icon_draw: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/ui/icon_draw.png',
  icon_gold: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/ui/icon_gold.png',
  icon_hp: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/ui/icon_hp.png',
  icon_mana: 'https://raw.githubusercontent.com/Seyferkun/ArcanaEternal/main/assets/ui/icon_mana.png',
};

let loadedAssets = {};
let assetsLoaded = false;

function loadAssets(callback) {
  const keys = Object.keys(ASSETS);
  let loaded = 0;
  keys.forEach(key => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      loadedAssets[key] = img;
      loaded++;
      if (loaded === keys.length) { assetsLoaded = true; if (callback) callback(); render(); }
    };
    img.onerror = () => { loaded++; if (loaded === keys.length) { assetsLoaded = true; if (callback) callback(); } };
    img.src = ASSETS[key];
  });
}

function getEnemySprite(enemyKey) {
  const map = {
    skeleton: 'skeleton', bat: 'wolf', slime: 'slime', goblin: 'goblin',
    spider: 'spider', ghost: 'ghost', orc: 'orc', imp: 'dark_mage',
    mushroom: 'slime', knight: 'dark_knight', wraith: 'ghost',
    dark_paladin: 'dark_knight', twin_assassins: 'orc', golem: 'golem',
    vampire: 'dark_knight', harpy: 'harpy', fire_elemental: 'fire_elemental',
    bandit: 'bandit', treant: 'treant', merman: 'merman',
    lich: 'boss_lich', dragon: 'boss_dragon', void_entity: 'boss_demon'
  };
  return map[enemyKey] || 'skeleton';
}

function getCardArt(cardId) {
  if (loadedAssets[cardId]) return loadedAssets[cardId];
  return null;
}